const ENV = {
	NEXT_PUBLIC_REQUEST_BASE_QUERY: process.env.NEXT_PUBLIC_REQUEST_BASE_QUERY,
	NEXT_PUBLIC_SESSION_SECRET_KEY: process.env.NEXT_PUBLIC_SESSION_SECRET_KEY,
} as {
	NEXT_PUBLIC_REQUEST_BASE_QUERY: string
	NEXT_PUBLIC_SESSION_SECRET_KEY: string
}

export default ENV
