const ENV = {
	REQUEST_BASE_QUERY_DEV: process.env.REQUEST_BASE_QUERY_DEV,
	REQUEST_BASE_QUERY_PROD: process.env.REQUEST_BASE_QUERY_PROD,
} as { REQUEST_BASE_QUERY_DEV: string; REQUEST_BASE_QUERY_PROD: string }

export default ENV
