services:
    todos-ui:
        container_name: todos-ui.prod
        image: todos-ui
        env_file:
            - .env.production
        build:
            context: .
        ports:
            - 3000:3000
