services:
    todos-ui:
        container_name: todos-ui.dev
        image: todos-ui
        env_file:
            - .env.development
        build:
            context: .
            target: builder # This is the key change: it tells Docker to only build and use the `builder` stage
        ports:
            - "3000:3000"
        command: npx next dev
