name: Integration Stage
run-name: ${{ github.repository }} start building by ${{github.actor}}...
on:
    pull_request:
        types:
            - closed
        branches:
            - int
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Testing "
